### ISSUE TITLE
Implement bidirectional intermittent data communication with server in OkHttp

### ISSUE THREAD

**Issue by tiagomartinhoo** [intelligent-personalized-care/ipc#10]
Create a WebSocket on Android with OkHttp to establish a bidirectional communication with the server, avoiding polling requests.

**Comment by RodrigoNevesWork** [comment]
The goal of this issue was accomplish using the SSE emitter of Spring. Polling no longer necesseary.

**Comment by tiagomartinhoo** [comment]
the commit ab9a66dd603eed0b60bee8f72e59b9c90b80fb33 solved this issue
